[project]
name = "february-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "guppylang[pytket]>=0.21.8",
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.3",
    "matplotlib>=3.10.8",
]
